package me.qcuncle.nowinnews.ui.theme

import androidx.compose.ui.graphics.Color

object Color0 {
    val md_theme_light_primary = Color(0xFFA73257)
    val md_theme_light_onPrimary = Color(0xFFFFFFFF)
    val md_theme_light_primaryContainer = Color(0xFFFFD9DF)
    val md_theme_light_onPrimaryContainer = Color(0xFF3F0017)
    val md_theme_light_secondary = Color(0xFF75565C)
    val md_theme_light_onSecondary = Color(0xFFFFFFFF)
    val md_theme_light_secondaryContainer = Color(0xFFFFD9DF)
    val md_theme_light_onSecondaryContainer = Color(0xFF2B151A)
    val md_theme_light_tertiary = Color(0xFF7A5732)
    val md_theme_light_onTertiary = Color(0xFFFFFFFF)
    val md_theme_light_tertiaryContainer = Color(0xFFFFDCBD)
    val md_theme_light_onTertiaryContainer = Color(0xFF2C1600)
    val md_theme_light_error = Color(0xFFBA1A1A)
    val md_theme_light_errorContainer = Color(0xFFFFDAD6)
    val md_theme_light_onError = Color(0xFFFFFFFF)
    val md_theme_light_onErrorContainer = Color(0xFF410002)
    val md_theme_light_background = Color(0xFFFFFBFF)
    val md_theme_light_onBackground = Color(0xFF201A1B)
    val md_theme_light_surface = Color(0xFFFFFBFF)
    val md_theme_light_onSurface = Color(0xFF201A1B)
    val md_theme_light_surfaceVariant = Color(0xFFF3DDE0)
    val md_theme_light_onSurfaceVariant = Color(0xFF524345)
    val md_theme_light_outline = Color(0xFF847375)
    val md_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
    val md_theme_light_inverseSurface = Color(0xFF352F30)
    val md_theme_light_inversePrimary = Color(0xFFFFB1C1)
    val md_theme_light_shadow = Color(0xFF000000)
    val md_theme_light_surfaceTint = Color(0xFFA73257)
    val md_theme_light_outlineVariant = Color(0xFFD6C2C4)
    val md_theme_light_scrim = Color(0xFF000000)

    val md_theme_dark_primary = Color(0xFFFFB1C1)
    val md_theme_dark_onPrimary = Color(0xFF66002A)
    val md_theme_dark_primaryContainer = Color(0xFF881840)
    val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DF)
    val md_theme_dark_secondary = Color(0xFFE4BDC3)
    val md_theme_dark_onSecondary = Color(0xFF43292F)
    val md_theme_dark_secondaryContainer = Color(0xFF5B3F45)
    val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DF)
    val md_theme_dark_tertiary = Color(0xFFECBE91)
    val md_theme_dark_onTertiary = Color(0xFF462A09)
    val md_theme_dark_tertiaryContainer = Color(0xFF60401D)
    val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBD)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF201A1B)
    val md_theme_dark_onBackground = Color(0xFFECE0E0)
    val md_theme_dark_surface = Color(0xFF201A1B)
    val md_theme_dark_onSurface = Color(0xFFECE0E0)
    val md_theme_dark_surfaceVariant = Color(0xFF524345)
    val md_theme_dark_onSurfaceVariant = Color(0xFFD6C2C4)
    val md_theme_dark_outline = Color(0xFF9E8C8F)
    val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
    val md_theme_dark_inverseSurface = Color(0xFFECE0E0)
    val md_theme_dark_inversePrimary = Color(0xFFA73257)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFFFFB1C1)
    val md_theme_dark_outlineVariant = Color(0xFF524345)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFFFB7397)

}